name: Generate Apps JSON

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Fetch release info
        run: |
          curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest > release.json
          jq '.assets | map({
              name: .name,
              version: "1.0.0",
              description: "No description available.",
              size: (.size / 1048576 | tostring + " MB"),
              updated: .updated_at,
              sdk: "Android",
              icon: "icons/default.png",
              file: .browser_download_url,
              hash: "N/A"
          })' release.json > apps.json

      - name: Commit JSON
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add apps.json
          git commit -m "Update apps.json from latest release" || echo "No changes"
          git push